---
- name: restart_postgres
  service:
    name: postgresql
    state: reloaded
    
- name: restart_supervisor
  service:
    name: supervisor
    state: reloaded

- name: ckan_tmp_dir_writable
  file:
    path: '/tmp/'
    mode: '666' # all r+w
    recurse: yes
    state: directory

- name: ckan_dir_webassets_writable
  file:
    path: '/tmp/'
    mode: '666' # all r+w
    recurse: yes
    state: directory
