---
# venv
- name: 01 create CKAN app dir
  file:
    path: '{{ ckan_app_dir }}'
    mode: ug+rwx
    owner: root
    group: root
    state: directory

- name: 02 Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3

- name: 03 pip install setuptools
  pip:
    name: 'setuptools==44.1.0'
    virtualenv: '{{ ckan_app_dir }}'
    virtualenv_python: 'python3.7'
    state: present

- name: 04 install ckan
  pip:
    name: 'git+https://github.com/ckan/ckan.git@ckan-2.9.4#egg=ckan[requirements]'
    virtualenv: '{{ ckan_app_dir }}'
    virtualenv_python: python3.7
    editable: yes   # --editable <path/url>   Install a project in editable mode
    state: present

# postgres
- name: 05 Postgres packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-psycopg2
    - postgresql
    - postgresql-client
    - postgresql-contrib
  notify: restart_postgres

- name: 06 Postgres user
  become_user: postgres
  become: yes
  postgresql_user:
    name: '{{ ckan_db_user }}'
    password: '{{ ckan_db_pwd }}'
    expires: 'infinity'

- name: 07 Postgres db
  become: yes
  become_user: postgres
  postgresql_db:
    name: '{{ ckan_db }}'
    encoding: UTF-8

- name: 08 Postgres user rights in db
  become: yes
  become_user: postgres
  postgresql_user:
    name: '{{ ckan_db_user }}'
    db: '{{ ckan_db }}'
    expires: 'infinity'
    state: present
    priv: ALL

#