---
# dcat extension

- name: pip install ckanext-harvest
  pip:
    name: 'git+https://github.com/ckan/ckanext-harvest.git#egg=ckanext-harvest'
    virtualenv: '{{ ckan_app_dir }}'
    virtualenv_python: python3.7
    editable: yes   # --editable <path/url>   Install a project in editable mode
    state: present

- name: pip install ckanext-harvest requirements
  pip:
    requirements: '{{ ckan_app_dir }}/src/ckanext-harvest/pip-requirements.txt'
    virtualenv: '{{ ckan_app_dir }}'
    virtualenv_python: 'python3.7'
    state: present

- name: ext dcat 01 - pip install ckanext-dcat
  pip:
    name: 'git+https://github.com/ckan/ckanext-dcat.git#egg=ckanext-dcat'
    virtualenv: '{{ ckan_app_dir }}'
    virtualenv_python: python3.7
    editable: yes   # --editable <path/url>   Install a project in editable mode
    state: present

- name: ext dcat 02 - pip install ckanext-dcat requirements
  pip:
    requirements: '{{ ckan_app_dir }}/src/ckanext-dcat/requirements.txt'
    virtualenv: '{{ ckan_app_dir }}'
    virtualenv_python: 'python3.7'
    state: present

- name: ext dcat 03 -Append ckanext-dcat to ckanplugins list
  set_fact:
   ckan_plugins: "{{ ckan_plugins + [item] }}"
  with_items:
   - "harvest"
   - "ckan_harvester"
   - "dcat"
   - "dcat_rdf_harvester"
   - "dcat_json_harvester"
   - "dcat_json_interface"
   - "structured_data"

- name: ext dcat 04 - update ckan.ini with ckanext-dcat settings
  community.general.ini_file:
    path: '{{ ckan_config_dir }}/ckan.ini'
    section: 'app:main'
    option: '{{ item.key }}'
    value: '{{ item.value }}' 
    backup: no
  with_dict: {
    ckan.plugins: '{{ ckan_plugins | join(" ")}}',
    'ckanext.dcat.enable_content_negotiation': 'True'
    }


- name: Create the harvester tables db
  command: '{{ ckan_app_dir }}/bin/ckan -c {{ ckan_config_dir }}/ckan.ini harvester initdb'
  register: dbtablescreate
  failed_when: "'DB tables created' not in dbtablescreate.stdout"

- name: ckan_harvesting.conf supervisor template
  template:
    src: ckan_harvesting.conf
    dest: /etc/supervisor/conf.d/ckan_harvesting.conf
    mode: og+wr
    owner: root
    group: root

- name: ext dcat 05 - restart supervisor
  service:
    name: supervisor
    state: reloaded
  notify: 
    - ckan_tmp_dir_writable
    - ckan_dir_webassets_writable

- name: ckan harvester cron # runs at 5AM
  cron:
    name: "ckan harvester"
    hour: "*5"
    job: '{{ ckan_app_dir }}/bin/ckan  -c {{ ckan_config_dir }}/ckan.ini harvester run > /dev/null'
  tags: localsettings


# chown www-data:www-data /usr/lib/ckan/default/src/ckan/ckan/public/base/i18n/*.js    