---
- name: 01 Install  datastore extension
  import_tasks: 01_datastore.yml

- name: 02 Install  datapusher extension
  import_tasks: 02_datapusher.yml

- name: 03 Install dcat extension
  import_tasks: 03_dcat.yml

- name: make writable dirs
  file:
    path: '{{ item }}'
    mode: 'a+rw'
    recurse: yes
    state: directory
  loop:
    - '/tmp'
    - '/var/opt/ckan/storage/uploads'

- name: test CKAN GET
  uri:
    url: '{{ ckan_intern_url }}'
    remote_src: yes
  register: _result
  until: _result.status == 200
  retries: 10 # 10 * 1 seconds
  delay: 1 # Every 1 second
