---
- name: 01 Install  datastore extension
  import_tasks: 01_datastore.yml

- name: 02 Install  datapusher extension
  import_tasks: 02_datapusher.yml

- name: 03 Install dcat extension
  import_tasks: 03_dcat.yml
