---
- name: restart_postgres
  service:
    name: postgresql
    state: reloaded
    
- name: restart_supervisor
  service:
    name: supervisor
    state: reloaded

- name: reload_webserver
  service:
    name: 'nginx'
    state: reloaded

- name: ckan_tmp_dir_writable
  file:
    path: '/tmp/{{ ckan_site_id }}'
    mode: 'a+rw'
    recurse: yes
    state: directory

- name: ckan_tmp_dir_writable
  file:
    path: '{{ ckan_app_dir }}/src/ckan/ckan/public/base/i18n/'
    owner: 'www-data'
    group: 'www-data'
    recurse: yes
    state: directory
