- hosts: all
  become: yes
  roles:
    - role: 01_utils
      tags:
        - utils
    - role: 02_ckan_core
      tags:
        - ckan
    - role: 03_ckan_extensions
      tags:
        - extensions
        - data_pusher_store
    - role: 04_nginx
      tags:
        - nginx